### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by ven1996** [mfouesneau/ezmist#4]
Your example code:    r = ezmist.get_t_isochrones(6.0, 7.0, 0.05, FeH_value=0.0, theory_output='full')

is showing error:      Interrogating http://waps.cfa.harvard.edu/MIST/iso_form.php...
                                Request...done.
                                Reading content...done.
                                list index out of range

**Comment by mfouesneau** [comment]
I cannot reproduce the issue:

```python
In [1]: import ezmist

In [2]: ezmist.get_t_isochrones(6.0, 7.0, 0.05, FeH_value=0.0, theory_output='full')
Interrogating http://waps.cfa.harvard.edu/MIST/iso_form.php...
Request...done.
Reading content...done.
Downloading data...http://waps.cfa.harvard.edu/MIST/tmp/MIST_iso_60e702c35d174.iso.zip...done.
b'PK\x03\x04\x14\x00\x00\x00\x08\x00iN\xe8R=\xf6\xfc\xbeb0m\x00\x98\xc9\x9d\x01\x1a\x00\x00\x00MIST_iso_60e702c35d174.iso\xd4\xfdM\x8fmMr\xa5\x07\xce\xf5+\x12\xd0\xb0\x9bW\xfe\xfd1\xd0\xa0\x07%\xa8\xd1%@Pk\xd2j4\x12Yd\x16\x8b\x00\x8b)$\xab\xd8' <class 'bytes'> b'PK\x03\x04\x14\x00\x00\x00\x08\x00'
decompressing archive (type=zip)...done.
Out[2]: 
<ezmist.simpletable.SimpleTable object at 0x106cbefa0>
Table: MIST/MESA isochrones
       nrows=10796, ncols=79, mem=6.47 MB
```

**Comment by mfouesneau** [comment]
Could you try again? Maybe this was a network or website temporary issue?

**Comment by ven1996** [comment]
Yeah, it is working fine now. Maybe it was the website's temporary issue. Because the single isochrone data was downloading, but "get_t_isochrones" was not working. 

Now it is working fine. Thank you...
